"""Basketball IQ scenarios, DNA category defs, archetype blueprints, gap->player study map."""

# IQ categories tracked
IQ_CATEGORIES = {
    "pick_and_roll": "Pick-and-Roll IQ",
    "shot_selection": "Shot Selection",
    "passing_reads": "Passing Reads",
    "help_defense": "Help-Defense IQ",
    "transition": "Transition IQ",
    "spacing": "Spacing IQ",
    "defensive_positioning": "Defensive Positioning",
    "closeout_reads": "Closeout Reads",
    "late_game": "Late-Game Decision-Making",
    "overall": "Overall Decision-Making",
}

DIFFICULTIES = ["Beginner", "Intermediate", "Advanced", "Elite"]


def _s(id, cat, diff, situation, options, correct, best, why, giving, notice, alts, game, position="Ball handler", context="Offense"):
    return {"id": id, "category": cat, "difficulty": diff, "situation": situation, "position": position,
            "context": context, "options": options, "correct": correct, "best_decision": best, "why": why,
            "defense_giving": giving, "should_notice": notice, "alternatives": alts, "game_application": game}


O = lambda a, b, c, d=None, e=None: [{"key": k, "text": t} for k, t in
                                      zip("ABCDE", [x for x in [a, b, c, d, e] if x is not None])]

SCENARIOS = [
    _s("pnr-drop-1", "pick_and_roll", "Beginner",
       "You're the ball handler at the top of the key. Your big sets a ball screen, your defender goes OVER the screen, and the opposing big DROPS deep toward the paint. The weak-side corner defender stays home.",
       O("Pull-up jumper off the screen", "Drive all the way into the drop big", "Pocket pass to the roller", "Reset the offense"),
       "A", "Pull-up jumper off the screen",
       "The drop big is protecting the rim, not stepping up to the level of the screen. With your defender trailing over the top, you have a clean window to rise into a pull-up before anyone contests.",
       "Space in the mid-range — the drop coverage concedes the pull-up to protect the paint.",
       "That no one is at the level of the screen to contest your rise, and the corner help stayed home so a drive is crowded.",
       ["C"], "Against drop coverage, a confident pull-up keeps the defense honest and forces them to change the scheme."),
    _s("pnr-hedge-1", "pick_and_roll", "Intermediate",
       "Ball screen at the wing. The big HEDGES hard out at you, momentarily trapping. Your roller slips to the rim and the low defender steps up to tag him. The weak-side corner is now open.",
       O("Split the hedge and attack", "Pocket pass to the roller", "Skip pass to the weak-side corner", "Pick up your dribble"),
       "C", "Skip pass to the weak-side corner",
       "The low man tagged the roller, which means the shooter he left — the weak-side corner — is now open. The advantage the defense created by trapping is punished one pass away.",
       "The weak-side corner three, because the help defender rotated off it to tag the roll.",
       "The chain reaction: hedge → roller slips → low man tags → corner opens. Read the SECOND defender, not the first.",
       ["B"], "Trapping coverages are beaten by the extra pass — find the open man the rotation left behind."),
    _s("pnp-1", "pick_and_roll", "Intermediate",
       "Pick-and-POP. Your big screens then pops to the three-point line. Your defender goes under the screen and the big's defender stays attached to the popping big.",
       O("Pull up from three immediately", "Throw it to the popped big", "Drive into the open lane", "Call for a re-screen"),
       "C", "Drive into the open lane",
       "Two defenders are occupied — yours went under and the big's man followed the pop. That empties the lane. The drive is the highest-value read before help can rotate.",
       "A wide-open driving lane, because both on-ball defenders vacated the paint.",
       "Going under a screen invites the drive, and the popping big pulled his defender out of help position.",
       ["A", "B"], "When your defender goes under and the screener's man follows the pop, attack the vacated paint."),
    _s("shot-sel-1", "shot_selection", "Beginner",
       "Early shot clock (18 seconds). You catch on the wing, contested closeout, and you're a 32% three-point shooter. A teammate is cutting backdoor and the offense hasn't developed.",
       O("Shoot the contested three", "Attack the closeout", "Hit the backdoor cutter", "Swing it and keep the offense moving"),
       "C", "Hit the backdoor cutter",
       "A backdoor cut against an aggressive closeout is a layup — the highest-value shot available. A contested three from a below-average shooter this early is a poor process shot.",
       "A layup via the backdoor, because the defender is flying at the closeout and turning his back to the cutter.",
       "The cutter, and that a contested early-clock three from a low percentage is exactly the shot the defense wants you to take.",
       ["B", "D"], "Best-shot hierarchy: layup > open three > contested two. Take the cut when it's there."),
    _s("shot-sel-2", "shot_selection", "Advanced",
       "7 seconds on the shot clock. You have a step on your man mid-drive but the help big is set in the paint. You're a good floater shooter. A shooter spots up in the weak-side corner.",
       O("Charge into the set big", "Pull up for the floater", "Kick to the weak-side shooter", "Step back for a two"),
       "B", "Pull up for the floater",
       "The big is SET, so driving all the way is an offensive foul or a block. The floater gets over him before he can contest and beats the shrinking clock. The corner kick is also fine if the low man commits.",
       "The floater window — the big is set at the rim but hasn't stepped up to the floater level.",
       "That the help is set (no charge), and the clock is too low to reset — you must generate a quality shot now.",
       ["C"], "The floater is the counter to a drop/set big who takes away the rim but concedes the short mid-range."),
    _s("dk-1", "passing_reads", "Beginner",
       "Drive-and-kick. You beat your man baseline. The weak-side low defender rotates over to help at the rim. His man is the weak-side corner shooter.",
       O("Finish through the help", "Kick to the weak-side corner", "Throw a lob you're not sure about", "Pick up and reset"),
       "B", "Kick to the weak-side corner",
       "The help defender left the corner shooter to stop your drive. The simple, correct read is the kick to the man he abandoned for an open catch-and-shoot three.",
       "An open corner three, created by the help rotation off the shooter.",
       "Which defender rotated and, therefore, which shooter is now open.",
       [], "Drive to collapse the defense, then hit the shooter the helper left. Classic drive-and-kick."),
    _s("dk-2", "passing_reads", "Advanced",
       "You penetrate the gap. Both the low help AND the nail (middle) defender step in to wall off your drive. That leaves two players open: the weak-side corner and the top-of-key trailer.",
       O("Force a contested layup", "Bounce pass to the corner", "Hit the trailer at the top for a swing", "Jump pass into traffic"),
       "C", "Hit the trailer at the top",
       "When two defenders commit, the ball should find the man whose pass leads to the next advantage. The top trailer catches on the move and can swing to the corner — a 'one more' pass that beats the closeout entirely.",
       "Two open players; the higher-value read is the one that keeps the ball moving ahead of the rotation (hockey assist).",
       "That two defenders stunted, so a shooter is open — and the top pass creates an even better shot than the corner.",
       ["B"], "Against two-man help, make the pass that forces the defense to rotate twice — the extra pass."),
    _s("help-1", "help_defense", "Beginner",
       "You're guarding the weak-side corner. The ball is driven baseline on the strong side toward the rim and your teammate is beaten.",
       O("Stay glued to your man", "Rotate to the rim (low-man help)", "Reach from behind for a steal", "Foul the driver"),
       "B", "Rotate to the rim (low-man help)",
       "You are the low man — your job is to stop the ball at the rim on baseline penetration. The next defender 'X-outs' to your man. Staying home concedes an easy layup.",
       "Nothing — this is a defensive read: the scheme demands the low man help on baseline drives.",
       "That you are the low/weak-side help and the driver has beaten his man to the rim.",
       [], "Low-man help stops the ball; trust the X-out rotation behind you to cover the shooter."),
    _s("help-2", "help_defense", "Advanced",
       "Ball is driven middle. You're one pass away on the weak side (the 'nail'). If you help, you leave a 40% shooter. If you don't, it's a layup. The driver is a poor finisher and a non-shooter is in the dunker spot.",
       O("Full commit and leave the shooter", "Stunt-and-recover (fake help)", "Do nothing, stay on the shooter", "Switch onto the driver"),
       "B", "Stunt-and-recover (fake help)",
       "A stunt shows help to make the driver pick up the ball or alter his angle, then you recover to your shooter. Since the driver is a poor finisher, you don't need to fully commit and give up the higher-value three.",
       "The choice between two threats; the driver being a weak finisher means a stunt is enough — don't over-help off a shooter.",
       "The driver's finishing ability and the shooter's ability — help decisions weigh WHO you're leaving.",
       ["A"], "Great help defenders stunt off shooters against weak finishers instead of fully rotating."),
    _s("closeout-1", "closeout_reads", "Beginner",
       "Your man catches on the wing behind the arc. You're closing out. He's a knock-down shooter but a shaky driver, and you have a set big behind you at the rim.",
       O("Fly at him out of control", "Close out high with a high hand, force the drive", "Close out short and give the three", "Foul the shooter"),
       "B", "Close out high with a high hand, force the drive",
       "Against a shooter who can't drive, you run him off the line with a high contest and funnel him into your rim protection. Closing out short concedes his best shot.",
       "You're deciding what to take away; against a shooter-not-driver, take away the three and live with the drive into your big.",
       "The scouting read: this man's a shooter first, so contest high and force him off the line.",
       [], "Close out to the shooter's weakness — high and short-strided on shooters, low and balanced on drivers."),
    _s("closeout-2", "closeout_reads", "Intermediate",
       "You're closing out to a 28% three-point shooter who is an explosive driver. No help is behind you.",
       O("Contest hard at the arc", "Close out under control, sit on the drive", "Go for the block on his shot", "Turn and run to the paint"),
       "B", "Close out under control, sit on the drive",
       "He can't shoot but he can blow by you, and there's no help. Break down under control and take away the drive; concede the low-percentage three you actually want him to take.",
       "The drive is the danger, not the shot — so protect against penetration, not the arc.",
       "His tendencies (poor shooter, explosive driver) and that there's no help to protect the rim.",
       [], "Closeouts are scouting-driven: give the bad shooter the shot, wall off the good driver."),
    _s("trans-1", "transition", "Beginner",
       "You grab a defensive rebound and push. It's a 3-on-2 fast break. Two defenders are back — one at the level of the free-throw line, one at the rim.",
       O("Attack the front defender to make him commit", "Pull up for a transition three immediately", "Slow it down and wait for everyone", "Throw a home-run pass"),
       "A", "Attack the front defender to make him commit",
       "In a 3-on-2, you attack the top defender to force him to choose — commit to you and you hit the wing; drop and you have a pull-up. Making the first defender wrong creates the advantage.",
       "A numbers advantage; you turn 3-on-2 into an easy look by forcing the top defender to make a decision.",
       "The 2 defenders' alignment and that pushing tempo before the defense sets is the whole point of the break.",
       [], "In 3-on-2, read the top defender: attack him to the level he defends, then make the right pass or finish."),
    _s("trans-d-1", "transition", "Intermediate",
       "You're the only defender back against a 2-on-1 fast break. Both attackers are filling lanes.",
       O("Commit to the ball handler", "Fake at the ball then protect the rim", "Foul immediately", "Back-pedal to the rim and force a pass"),
       "B", "Fake at the ball then protect the rim",
       "As the lone defender you must delay and buy time for help. Fake at the ball to stall the handler, then retreat to take away the layup, forcing a jumper or a tough pass.",
       "Nothing willingly — your job is to turn an easy 2 into the hardest possible shot while help arrives.",
       "That you're outnumbered: delay, don't gamble, and protect the rim first.",
       ["D"], "Lone-back defense: stunt to slow the ball, then sink to force the pull-up, never bite on the first move."),
    _s("spacing-1", "spacing", "Beginner",
       "You're on the weak-side wing. A teammate drives baseline toward your side of the floor and is about to draw help.",
       O("Cut to the same spot to help", "Lift/relocate to keep spacing and a passing lane", "Stand still", "Set a random screen"),
       "B", "Lift/relocate to keep spacing and a passing lane",
       "As the drive comes to your side you relocate along the arc to stay in the driver's vision and out of the helper's reach — giving him an outlet and stretching the defense.",
       "Nothing given — this is an offensive spacing habit that turns a drive into an open kick.",
       "That crowding the drive brings your defender into help; relocating keeps the floor spaced and a lane open.",
       [], "Good spacing = move to stay open on drives. Drift/lift into the ball handler's sightline."),
    _s("spacing-2", "spacing", "Advanced",
       "You're in the strong-side corner. Your teammate is posting up on your block and gets doubled from the baseline — by YOUR man.",
       O("Stay in the corner", "Lift to the wing for a better passing angle", "Cut to the rim", "Go set a screen away"),
       "B", "Lift to the wing for a better passing angle",
       "Your defender left the corner to double the post. Lifting from the corner to the wing gives the post a cleaner passing angle out of the double and a rhythm catch-and-shoot as you're already open.",
       "An open shot — your man doubled the post, so you relocate to receive the kick-out in rhythm.",
       "Who is doubling (your man) and that a slight relocation improves the passing angle out of the trap.",
       ["A"], "When your man leaves to double, relocate to the best passing window, don't just stand where you were."),
    _s("dpos-1", "defensive_positioning", "Beginner",
       "You're guarding a non-shooter one pass away while the ball is on the wing. Your man is in the strong-side corner.",
       O("Deny tight, face-guard him", "Sit in the gap in help position", "Turn your back to the ball", "Full-front him"),
       "B", "Sit in the gap in help position",
       "One pass away from a non-shooter, you play off in the gap — able to help on drives and still recover. Denying a non-shooter tightly removes your help value for no reason.",
       "This is positioning IQ — off a non-shooter you prioritize gap help over tight denial.",
       "That your man can't shoot, so ball-you-man spacing lets you help without giving up anything.",
       [], "Position off your man's ability: gap off non-shooters, tighten up on shooters."),
    _s("dpos-2", "defensive_positioning", "Elite",
       "Off-ball, your man (a shooter) is in the weak-side corner. The ball handler starts a middle drive. Help rules say you're the low tag on the roller, but your man is a 44% corner shooter.",
       O("Fully commit to tag the roller", "High stunt and recover to the shooter", "Ignore the roll, stay on shooter", "Switch onto the roller and give up the corner"),
       "B", "High stunt and recover to the shooter",
       "Elite weak-side defense balances two threats. A short stunt discourages the pocket pass to the roller while keeping you close enough to contest the 44% corner three — the higher-value shot.",
       "A choice between the roll and the corner; the shooter's high percentage means you can't fully vacate the corner.",
       "The shooter's value vs the roller's value — great defenders don't over-help off elite shooters.",
       ["A"], "Weak-side reads weigh shooter quality — stunt-and-recover against elite corner shooters."),
    _s("post-entry-1", "passing_reads", "Intermediate",
       "You want to enter the ball to your post who has deep position. The defender is fronting (playing between you and the post). The weak-side help is one pass away.",
       O("Force a bounce pass through the front", "Skip to the opposite wing to change the angle, then enter", "Lob over the top immediately", "Abandon the post entry"),
       "B", "Skip to the opposite wing to change the angle",
       "Against a full front, changing the ball's angle with a quick reversal forces the defender to re-establish position and opens a clean entry or an over-the-top lob with the help now out of position.",
       "The front takes away the direct entry, but reversing the ball beats the fronting defender's position.",
       "That the defender is fronting and the weak-side help is the one who'd take the lob — move the ball to move the help.",
       ["C"], "Beat a fronted post by reversing the ball; the front can't hold position when the angle changes."),
    _s("double-1", "passing_reads", "Advanced",
       "You catch on the block and a hard double comes from the top. You feel it late. Your options: the man the doubler left (top of key) and a baseline cutter.",
       O("Split the double with a dribble", "Kick to the man at the top the doubler left", "Force a shot over two", "Throw baseline without looking"),
       "B", "Kick to the man at the top",
       "The double came from the top, so the open man is the one the doubler vacated. Passing OUT and UP restarts the offense with a 4-on-3 the other way.",
       "A 4-on-3 advantage — one defender left his man to double, so that man is free.",
       "Where the double came FROM, because that tells you exactly who is open.",
       ["A"], "Beat doubles by passing to the man the trapper left, then play out of the advantage."),
    _s("late-clock-1", "late_game", "Intermediate",
       "3 seconds on the shot clock. You have the ball 25 feet out, guarded tightly, no advantage.",
       O("Drive hard for a layup you won't reach", "Get into a step-back and rise before the buzzer", "Pass it to a covered teammate", "Hold it and force a heave"),
       "B", "Get into a step-back and rise before the buzzer",
       "With 3 seconds and no advantage, you must generate a shot NOW. A step-back creates just enough separation to get a decent look off before the shot-clock violation — the best available process.",
       "Nothing — the clock forces the action; your job is the best possible shot in the time left.",
       "The clock. Late-clock possessions are about getting a clean attempt up, not a perfect one.",
       ["A"], "Late-clock: know the time and manufacture a shot; a rushed heave or a pass to a covered man wastes the possession."),
    _s("late-game-1", "late_game", "Advanced",
       "Down 2, 12 seconds left, no timeouts. You have it in the backcourt. The defense is set but not pressing hard.",
       O("Rush a quick three right now", "Push with pace, attack before the defense loads, take the best 2 or kicked three", "Walk it up and iso with 3 seconds", "Call a timeout you don't have"),
       "B", "Push with pace and attack before the defense loads",
       "Down 2, a two ties and a three wins, so you don't need to rush a three. Pushing tempo attacks the defense before it's fully set, generating a high-quality look with time for an offensive rebound.",
       "A not-yet-loaded defense — pace creates a better shot than a walk-it-up iso with no margin for a miss.",
       "The score (down 2 = a two is fine), the clock, and that early offense beats a predictable late iso.",
       ["A"], "Down 2 late: play with pace for a great look and leave time to rebound; don't settle for a hero three unless it's clean."),
    _s("iso-1", "shot_selection", "Intermediate",
       "Isolation at the wing against a set defender. You have a slight size advantage. The help is one pass away, sagging off a non-shooter in the corner.",
       O("Settle for a contested step-back", "Attack the mismatch to the rim/mid-post", "Wait and let the clock run", "Pass out and re-iso"),
       "B", "Attack the mismatch to the rim/mid-post",
       "With a size edge and the only help coming off a non-shooter (who you can pass to if help commits), the highest-value play is to attack the mismatch downhill rather than settle for a contested jumper.",
       "A one-on-one you can win, with a safety valve if the sagging help commits.",
       "Your advantage (size), and that the help is off a non-shooter, so a drive is well-supported.",
       ["A"], "Iso wisely: attack the actual advantage; only settle for the step-back when the drive is truly walled off."),
    _s("switch-1", "defensive_positioning", "Advanced",
       "Ball screen. You're defending the screener (a big). Your team's scheme is to SWITCH. After the switch you're now on a quick guard 25 feet out with a runway behind you.",
       O("Pressure him tight at the arc", "Give a cushion and sit on the drive, funnel to help", "Reach for a steal", "Immediately call for another switch"),
       "B", "Give a cushion and sit on the drive",
       "As a big switched onto a quick guard, your danger is getting blown by. Give a cushion to take away the blow-by, contain the ball, and funnel toward help until your teammate can switch back or dig.",
       "The guard wants your feet — a cushion removes the blow-by and buys time.",
       "The mismatch (slower feet), so you protect against speed, not the jumper.",
       [], "On a switch mismatch, a big drops a cushion and contains; a guard on a big fronts/digs before the catch."),
    _s("offball-1", "spacing", "Intermediate",
       "You're a shooter being guarded off the ball. Your defender turns his head to watch the ball on a strong-side drive.",
       O("Stand and call for the ball", "Backdoor cut behind his blind side", "Set a screen for the driver", "Drift further into the corner"),
       "B", "Backdoor cut behind his blind side",
       "When your defender turns his head and loses you, the read is to cut backdoor into the space behind him for a layup — punishing ball-watching before he recovers.",
       "A blind-side lane, because the defender lost vision of you to watch the ball.",
       "Your defender's eyes — off-ball scoring comes from reading when he stops seeing you.",
       ["D"], "Read the defender's eyes off the ball: cut backdoor when he ball-watches, relocate when he recovers."),
]

# ---------------- DNA categories ----------------
DNA_CATEGORIES = [
    ("shooting", "Shooting"), ("handle", "Handle"), ("creation", "Creation"), ("finishing", "Finishing"),
    ("playmaking", "Playmaking"), ("defense", "Defense"), ("footwork", "Footwork"),
    ("athleticism", "Athleticism"), ("basketball_iq", "Basketball IQ"), ("pace", "Pace"),
    ("decision_making", "Decision-Making"), ("off_ball", "Off-Ball Movement"),
    ("rebounding", "Rebounding"), ("post", "Post Play"),
]

# descriptor for a strong DNA category (used to build evolving labels)
DNA_DESCRIPTOR = {
    "shooting": "Sniper", "handle": "Handle Artist", "creation": "Creator", "finishing": "Finisher",
    "playmaking": "Playmaker", "defense": "Stopper", "basketball_iq": "Floor General",
    "pace": "Downhill Threat", "off_ball": "Movement Threat", "decision_making": "Decision Maker",
}

# ---------------- Archetype blueprints ----------------
# emphasis: DNA categories that define the archetype (weights). skills/players reference existing data.
def _bp(name, emphasis, skills, habits, iq_focus, players, summary):
    return {"name": name, "emphasis": emphasis, "skills": skills, "habits": habits,
            "iq_focus": iq_focus, "players": players, "summary": summary}

ARCHETYPE_BLUEPRINTS = {
    "Iso Sniper": _bp("Iso Sniper",
        {"shooting": 0.3, "creation": 0.3, "handle": 0.2, "footwork": 0.1, "decision_making": 0.1},
        ["stepback", "pull-up", "face-up-jab", "crossover"],
        ["Create separation off the dribble", "Weak-hand counters", "Deceleration into the pull-up"],
        ["shot_selection", "pick_and_roll"], ["kobe-bryant", "kevin-durant", "michael-jordan"],
        "A self-creating shot-maker who generates efficient looks in isolation off the dribble."),
    "Three-Level Scorer": _bp("Three-Level Scorer",
        {"shooting": 0.25, "creation": 0.2, "finishing": 0.25, "handle": 0.15, "decision_making": 0.15},
        ["pull-up", "floater", "eurostep", "stepback"],
        ["Finish through contact", "Mid-range mastery", "Read the coverage before you attack"],
        ["shot_selection", "pick_and_roll"], ["kevin-durant", "kobe-bryant", "luka-doncic"],
        "Scores efficiently at the rim, mid-range, and three — nearly impossible to key on one level."),
    "Movement Sniper": _bp("Movement Sniper",
        {"shooting": 0.35, "off_ball": 0.3, "footwork": 0.15, "pace": 0.1, "decision_making": 0.1},
        ["off-screen-shooting", "catch-shoot", "pull-up"],
        ["Sprint off screens with feet ready", "Relocate off the ball", "Conditioning to run all game"],
        ["spacing", "shot_selection"], ["stephen-curry", "larry-bird", "damian-lillard"],
        "Punishes defenses by never standing still — comes off screens and relocations for quick-trigger threes."),
    "Floor General": _bp("Floor General",
        {"playmaking": 0.3, "basketball_iq": 0.25, "decision_making": 0.2, "pace": 0.15, "handle": 0.1},
        ["pnr-read", "pocket-pass", "hesitation"],
        ["Control tempo", "Set teammates up in their spots", "Protect the ball"],
        ["pick_and_roll", "passing_reads", "transition"], ["chris-paul", "magic-johnson", "nikola-jokic"],
        "Runs the offense — reads coverages, controls pace, and makes everyone around better."),
    "Scoring PG": _bp("Scoring PG",
        {"creation": 0.25, "shooting": 0.25, "handle": 0.2, "playmaking": 0.15, "decision_making": 0.15},
        ["crossover", "stepback", "pull-up", "pnr-read"],
        ["Score AND create off the ball screen", "Change of pace", "Late-clock shot creation"],
        ["pick_and_roll", "shot_selection"], ["damian-lillard", "luka-doncic", "james-harden"],
        "A lead guard who scores at volume while still running the pick-and-roll."),
    "Rim Attacker": _bp("Rim Attacker",
        {"finishing": 0.35, "handle": 0.2, "athleticism": 0.2, "creation": 0.15, "decision_making": 0.1},
        ["eurostep", "floater", "reverse-layup", "pro-hop", "in-and-out"],
        ["Downhill first step", "Finish through/around length", "Change speeds to the rim"],
        ["shot_selection", "transition"], ["giannis-antetokounmpo", "allen-iverson", "lebron-james"],
        "Lives in the paint — beats defenders off the bounce and finishes through traffic."),
    "Lockdown Guard": _bp("Lockdown Guard",
        {"defense": 0.4, "athleticism": 0.2, "basketball_iq": 0.2, "footwork": 0.2},
        ["defensive-slide", "closeout"],
        ["Stay in a stance", "Navigate screens", "Active hands without fouling"],
        ["defensive_positioning", "closeout_reads", "help_defense"], ["kawhi-leonard", "scottie-pippen"],
        "Shuts down the primary perimeter threat with feet, discipline, and IQ."),
    "3-and-D Wing": _bp("3-and-D Wing",
        {"shooting": 0.3, "defense": 0.35, "off_ball": 0.15, "decision_making": 0.2},
        ["catch-shoot", "closeout", "defensive-slide"],
        ["Knock down the corner three", "Guard multiple positions", "Make the simple read"],
        ["closeout_reads", "defensive_positioning", "spacing"], ["kawhi-leonard", "scottie-pippen", "klay-thompson"],
        "The modern connector: spaces the floor and defends the other team's best wing."),
    "Point Forward": _bp("Point Forward",
        {"playmaking": 0.3, "creation": 0.2, "basketball_iq": 0.2, "finishing": 0.15, "decision_making": 0.15},
        ["pnr-read", "pocket-pass", "eurostep"],
        ["See the floor from the wing", "Push in transition", "Use size to post mismatches"],
        ["passing_reads", "pick_and_roll", "transition"], ["lebron-james", "magic-johnson", "luka-doncic"],
        "A forward who initiates offense — size, vision, and downhill force."),
    "Stretch Five": _bp("Stretch Five",
        {"shooting": 0.35, "post": 0.15, "playmaking": 0.15, "basketball_iq": 0.2, "decision_making": 0.15},
        ["catch-shoot", "pnr-read", "pick-and-pop"],
        ["Pop and space as a big", "Read the short roll", "Punish switches inside-out"],
        ["spacing", "pick_and_roll"], ["dirk-nowitzki", "nikola-jokic"],
        "A big who spaces the floor and can playmake out of the pick-and-pop."),
    "Defensive Anchor": _bp("Defensive Anchor",
        {"defense": 0.4, "basketball_iq": 0.2, "rebounding": 0.2, "athleticism": 0.2},
        ["box-out", "closeout"],
        ["Protect the rim", "Communicate coverages", "Rebound out of your area"],
        ["help_defense", "defensive_positioning"], ["tim-duncan", "hakeem-olajuwon"],
        "The back line of the defense — rim protection, rotations, and rebounding."),
    "Post Scorer": _bp("Post Scorer",
        {"post": 0.35, "footwork": 0.25, "finishing": 0.2, "basketball_iq": 0.2},
        ["dropstep", "jump-hook", "face-up-jab", "spin-move"],
        ["Establish deep position", "Counter off the first move", "Read the double"],
        ["passing_reads", "shot_selection"], ["hakeem-olajuwon", "shaquille-oneal", "tim-duncan"],
        "Dominates the block with footwork, touch, and counters."),
    "Two-Way Big": _bp("Two-Way Big",
        {"defense": 0.3, "finishing": 0.2, "rebounding": 0.2, "post": 0.15, "basketball_iq": 0.15},
        ["dropstep", "box-out", "closeout"],
        ["Anchor the D and finish the pick-and-roll", "Rebound both ends", "Screen and roll hard"],
        ["help_defense", "defensive_positioning", "pick_and_roll"], ["tim-duncan", "giannis-antetokounmpo"],
        "Impacts both ends — protects the rim and scores efficiently inside."),
    "Pull-Up Sniper": _bp("Pull-Up Sniper",
        {"shooting": 0.35, "creation": 0.25, "handle": 0.2, "decision_making": 0.2},
        ["pull-up", "stepback", "crossover", "hesitation"],
        ["Rise off one/two dribbles", "Balanced base on the pull-up", "Punish drop coverage"],
        ["pick_and_roll", "shot_selection"], ["damian-lillard", "stephen-curry", "kevin-durant"],
        "Deadly off the dribble — makes defenses pay for going under or dropping."),
    "Pick-and-Roll Maestro": _bp("Pick-and-Roll Maestro",
        {"playmaking": 0.3, "basketball_iq": 0.25, "creation": 0.2, "decision_making": 0.25},
        ["pnr-read", "pocket-pass", "floater", "hesitation"],
        ["Read the two defenders", "Manipulate pace off the screen", "Punish every coverage"],
        ["pick_and_roll", "passing_reads"], ["chris-paul", "luka-doncic", "magic-johnson"],
        "Masters the ball screen — reads every coverage and makes the right play every time."),
    "Downhill Creator": _bp("Downhill Creator",
        {"finishing": 0.3, "creation": 0.25, "athleticism": 0.2, "handle": 0.15, "decision_making": 0.1},
        ["eurostep", "in-and-out", "pro-hop", "pocket-pass"],
        ["Play with force and pace", "Collapse the defense then kick", "Finish through help"],
        ["transition", "passing_reads", "shot_selection"], ["giannis-antetokounmpo", "lebron-james", "luka-doncic"],
        "Gets downhill relentlessly, bends the defense, and finishes or creates for others."),
}

# gap keyword -> existing player ids to study (Player Lab links)
GAP_PLAYERS = {
    "shooting": ["stephen-curry", "damian-lillard", "dirk-nowitzki", "kevin-durant"],
    "off_ball": ["stephen-curry", "larry-bird", "kevin-durant"],
    "handle": ["allen-iverson", "luka-doncic", "chris-paul"],
    "creation": ["kobe-bryant", "james-harden", "luka-doncic"],
    "finishing": ["giannis-antetokounmpo", "allen-iverson", "shaquille-oneal"],
    "playmaking": ["chris-paul", "magic-johnson", "nikola-jokic"],
    "defense": ["kawhi-leonard", "scottie-pippen", "tim-duncan"],
    "footwork": ["hakeem-olajuwon", "kobe-bryant", "tim-duncan"],
    "basketball_iq": ["chris-paul", "magic-johnson", "nikola-jokic"],
    "decision_making": ["chris-paul", "lebron-james", "nikola-jokic"],
    "pace": ["chris-paul", "luka-doncic"],
    "post": ["hakeem-olajuwon", "shaquille-oneal", "tim-duncan"],
    "athleticism": ["giannis-antetokounmpo", "lebron-james"],
    "rebounding": ["tim-duncan", "shaquille-oneal"],
}
