"""Seed data for Elite AI Basketball Coach: skills, players, archetypes, daily pool, badges."""

ARCHETYPES = [
    "Movement Sniper", "Pull-Up Sniper", "Deep-Range Sniper", "Iso Technician", "Iso Sniper",
    "Three-Level Scorer", "Point Forward", "Floor General", "Pick-and-Roll Maestro",
    "Downhill Creator", "Rim Attacker", "Craft Finisher", "Pace Manipulator", "Two-Way Wing",
    "Two-Way Big", "Lockdown Guard", "Defensive Anchor", "Rim Protector", "Post Scorer",
    "Passing Big", "Stretch Four", "Stretch Five", "Movement Shooter", "Handle Artist",
    "Catch-and-Shoot Specialist", "Combo Guard", "Glass Cleaner", "Mismatch Hunter", "Clutch Shot Maker",
]

DAILY_1PCT = [
    "10 perfect weak-hand pound dribbles - eyes up",
    "25 game-speed finishes at the rim - inside hand only",
    "Film 5 pull-up jumpers - check balance on landing",
    "Track every left-wing shot today",
    "20 deceleration stops from full sprint",
    "Review 5 possessions from your last session",
    "50 form shots from 5 feet - no legs",
    "10 minutes of change-of-direction reps at 75%",
    "Chart your shot selection for a full workout",
    "3 signature move reps at game speed against imaginary defender",
]

# 12 badges: (key, label, emoji)
BADGES = [
    ("first_step", "First Step", "\U0001F3C0"),
    ("streak_3", "3-Day Streak", "\U0001F525"),
    ("streak_7", "7-Day Streak", "\u26A1"),
    ("streak_14", "14-Day Streak", "\U0001F4AA"),
    ("streak_30", "30-Day Streak", "\U0001F451"),
    ("sessions_5", "5 Sessions", "\U0001F3AF"),
    ("sessions_20", "20 Sessions", "\U0001F3ED"),
    ("shots_100", "100 Shots", "\U0001F3AF"),
    ("shots_500", "500 Shots", "\U0001F319"),
    ("film_1", "First Film", "\U0001F3A5"),
    ("film_10", "Film Junkie", "\U0001F9E0"),
    ("coach_10", "Coachable", "\U0001F4AC"),
]

STREAK_MILESTONES = [3, 7, 14, 30]

# YouTube tutorial ids per skill slug
VIDEO_IDS = {
    "crossover": "IBm4cjgY5X8", "hesitation": "RTfMiMcq6Ag", "stepback": "Q41TgJNulYY",
    "eurostep": "NDkOwZXr2DY", "pnr-read": "gSy95y-SWmE", "closeout": "xI24HZ3yQHw",
    "dropstep": "kcwCvwCBU-A", "catch-shoot": "aGL5Yv5LYHs", "between-legs": "uySOXWH2Ruc",
    "behind-back": "kmYJIaHkmJo", "in-and-out": "r2DmMOW5KXA", "spin-move": "W7tSoukvNFs",
    "floater": "bx3HUC-6vhQ", "pull-up": "rsyjVzJrPKQ", "off-screen-shooting": "xYXvTuAMk8s",
    "free-throw": "0343D3fjPnQ", "reverse-layup": "58UOhVtAasY", "pro-hop": "79Wx1LPyxDg",
    "jump-hook": "jX8QU728yXo", "face-up-jab": "vgFnrBdWE2Y", "pocket-pass": "Xr4z05nC40Y",
    "defensive-slide": "QaYwcS00vSA", "box-out": "zZMQ6jiHNY8", "change-of-pace": "p9tBvO-rU78",
}


def _skill(slug, name, category, difficulty, when, why, how, mistakes, cues, counter, game):
    return {
        "slug": slug, "name": name, "category": category, "difficulty": difficulty,
        "when": when, "why": why, "how": how, "mistakes": mistakes, "cues": cues,
        "counter": counter, "game": game, "video_id": VIDEO_IDS[slug],
    }


SKILLS = [
    # ---------------- BALL HANDLING ----------------
    _skill("crossover", "Crossover", "Ball Handling", "Beginner",
        "When a defender overplays one hand or sits square and flat-footed on the perimeter.",
        "A hard, low crossover shifts the defender's weight to one side so you can attack the opposite hip before they recover.",
        ["Sell the drive one direction with your eyes, shoulder and a hard first step.",
         "Snap the ball across your body below the knee, ball hitting the floor close to your front foot.",
         "Catch it in the new hand and explode off the opposite foot into the gap.",
         "Keep your head and chest low and level through the switch."],
        ["Crossing the ball too high (above the knee) so it's easy to poke.",
         "Standing straight up, which removes all deception and burst."],
        ["Low and long", "Sell the first move", "Explode second step"],
        "If they jump the crossover, go behind-the-back or between-the-legs to keep the ball protected.",
        "Best against on-ball defenders who reach; devastating in isolation and off ball-screen rejects."),
    _skill("between-legs", "Between-the-Legs", "Ball Handling", "Intermediate",
        "When you need a protected direction change with a defender pressuring the ball tightly.",
        "Passing the ball between your legs keeps a barrier (your body and legs) between the ball and the defender's hands.",
        ["Get low with a wide, staggered stance.",
         "Push the ball through the gap timed with the opposite foot stepping forward.",
         "Catch on the far side and immediately read the defender's hips.",
         "Chain it into a crossover or attack if the lane opens."],
        ["Doing it too upright so the ball travels a long, exposed path.",
         "Telegraphing by pausing before the move."],
        ["Wide base", "Snap it through", "Read then react"],
        "Combine with a hesitation or in-and-out to freeze a defender who reads the rhythm.",
        "Great as a change-of-direction counter and to set up step-backs at the arc."),
    _skill("behind-back", "Behind-the-Back", "Ball Handling", "Intermediate",
        "When a defender cuts off your lead hand and you need to change direction without exposing the ball.",
        "Wrapping the ball behind your back hides it completely and lets you counter a defender who jumps your crossover.",
        ["Drop the shoulder as if continuing the drive.",
         "Wrap the ball around your back hip, pushing it to the far side.",
         "Catch in the new hand already stepping into the open lane.",
         "Stay low so you don't lose speed through the wrap."],
        ["Wrapping too wide and losing the ball behind you.",
         "Popping upright, which kills the drive angle."],
        ["Hide it", "Stay low", "Push, don't loop"],
        "If overplayed on the counter, snap back with a quick crossover into the original gap.",
        "Ideal in transition and on the sideline to escape trapping defenders."),
    _skill("in-and-out", "In-and-Out", "Ball Handling", "Beginner",
        "When a defender lunges at the ball or slides early to cut off a direction.",
        "A fake crossover (in-and-out) freezes the defender's feet, letting you attack the same side you started.",
        ["Bring the ball toward the middle like a crossover start.",
         "Roll your wrist over the top and keep it in the same hand.",
         "Push off the same-side foot and accelerate past the frozen defender.",
         "Keep the fake sharp and low to sell it."],
        ["Rolling the ball too slowly so it looks like a hesitation, not a fake.",
         "Losing the ball out front because the wrist doesn't cover the top."],
        ["Sell the cross", "Wrist over top", "Same-side burst"],
        "If they don't bite, chain straight into a real crossover or between-the-legs.",
        "A staple move for downhill creators attacking a flat-footed on-ball defender."),
    # ---------------- SHOOTING ----------------
    _skill("stepback", "Step-Back Jumper", "Shooting", "Advanced",
        "When a defender is riding your hip on a drive and you need separation for a clean look.",
        "Pushing off into a controlled step-back creates space from the defender while keeping your shooting balance.",
        ["Attack downhill to commit the defender's momentum forward.",
         "Plant hard off your inside foot and push back and slightly to the side.",
         "Gather the ball into your shooting pocket as you rise.",
         "Land balanced with feet set square to the rim."],
        ["Drifting sideways so your base is off-balance at release.",
         "Rushing the gather and short-arming the shot."],
        ["Sell the drive", "Push off hard", "Set your base"],
        "If the defender sits on the step-back, use a one-dribble pull-up going forward instead.",
        "A go-to shot-creation weapon for pull-up snipers and iso scorers."),
    _skill("catch-shoot", "Catch-and-Shoot", "Shooting", "Beginner",
        "When you spot up off a drive-and-kick or off-ball movement and receive the ball with space.",
        "A quick, repeatable catch-and-shoot turns advantages created by teammates into efficient points.",
        ["Show your hands and get feet ready (hop or 1-2) before the pass arrives.",
         "Catch the ball already in your shooting pocket.",
         "Rise straight up with a consistent release point.",
         "Hold your follow-through and land where you jumped."],
        ["Catching flat-footed and then gathering, which is slow.",
         "Fading or drifting instead of going straight up."],
        ["Feet ready early", "Catch in the pocket", "Straight up"],
        "If the closeout is hard, shot-fake and attack the closeout for a one-dribble pull-up.",
        "The bread-and-butter of movement shooters and floor-spacing specialists."),
    _skill("pull-up", "Pull-Up Jumper", "Shooting", "Intermediate",
        "When the defender goes under a screen or gives a cushion on the drive.",
        "A balanced pull-up off the dribble punishes defenders who sag and keeps them honest on your handle.",
        ["Get downhill with a purposeful gather dribble.",
         "Dip the ball into your pocket as you plant both feet.",
         "Rise vertically, not forward, keeping your head over your base.",
         "Follow through and land in the same spot."],
        ["Drifting forward into the defender.",
         "Not gathering into the pocket, causing a low or flat release."],
        ["Gather dribble", "Rise vertical", "Balanced base"],
        "If they trail hard over the screen, keep the drive and finish or kick.",
        "Essential for pull-up snipers and three-level scorers in the mid-range and off ball screens."),
    _skill("off-screen-shooting", "Shooting Off Screens", "Shooting", "Advanced",
        "When running off a pin-down, flare, or wide pin to get open away from the ball.",
        "Coming off screens with your feet and hands ready lets you launch before the defender recovers.",
        ["Set up your cut by walking your defender in before sprinting off the screen.",
         "Get your inside foot down first (the 1-2) as you come off.",
         "Have hands up as a target before the catch.",
         "Turn your shoulders square and rise immediately."],
        ["Coming off the screen slow and upright.",
         "Catching without feet prepared, forcing an extra beat."],
        ["Set up the cut", "Inside foot first", "Feet and hands ready"],
        "If the defender trails, curl to the rim; if they go over the top, flare for the shot.",
        "The signature skill of movement snipers like off-ball guards and shooting specialists."),
    _skill("free-throw", "Free Throw", "Shooting", "Beginner",
        "Every trip to the line - the most repeatable, un-guarded shot in the game.",
        "A locked-in free-throw routine converts free points and steadies your mechanics under fatigue.",
        ["Set the same foot alignment and ball position every time.",
         "Take the same number of dribbles and a deep breath (your routine).",
         "Focus your eyes on a single target on the rim.",
         "Shoot with legs and hold your follow-through."],
        ["Changing your routine under pressure.",
         "Relying only on arms when tired instead of using your legs."],
        ["Same routine", "Eyes on target", "Legs into it"],
        "There is no counter - the answer is reps and an unbreakable routine.",
        "Free throws decide close games; elite scorers live at the line."),
    # ---------------- FINISHING ----------------
    _skill("eurostep", "Euro Step", "Finishing", "Intermediate",
        "When driving into a help defender who is stepping up to take a charge or contest.",
        "A euro step uses a two-direction gather to step around the defender and finish at an open angle.",
        ["Pick up your dribble a step earlier than usual.",
         "Take your first step toward the defender to commit them one way.",
         "Swing your second step the opposite direction, past their hip.",
         "Finish with the hand away from the defender."],
        ["Traveling by picking up the ball too late or with a stutter.",
         "Making the first step too small to move the defender."],
        ["Gather early", "Big first step", "Finish away"],
        "If the defender slides with your second step, spin back or use a pro-hop into them.",
        "A core finishing tool for downhill creators and rim attackers in traffic."),
    _skill("floater", "Floater / Runner", "Finishing", "Advanced",
        "When a rim protector waits in the paint and you can't get all the way to the rim.",
        "A high, soft floater gets the ball over long defenders before they can rise to contest.",
        ["Gather off one foot on the move without slowing down.",
         "Rise off your inside foot, protecting the ball with your body.",
         "Push the ball high off your fingertips with soft backspin.",
         "Aim for the top of the square or high off the glass."],
        ["Shooting it flat so a shot-blocker can reach it.",
         "Fading away and losing touch and accuracy."],
        ["High and soft", "One-foot rise", "Fingertip touch"],
        "If the big drops all the way, pull up short for the mid-range instead.",
        "The great equalizer for smaller guards attacking bigger rim protectors."),
    _skill("reverse-layup", "Reverse Layup", "Finishing", "Intermediate",
        "When you drive baseline and a helper is between you and the front of the rim.",
        "Finishing on the far side of the basket uses the rim itself to shield the ball from the shot-blocker.",
        ["Attack under the rim along the baseline.",
         "Extend the ball to the opposite side of the backboard.",
         "Use the rim and net to protect the finish.",
         "Finish high off the glass with the outside hand."],
        ["Finishing too flat and letting the blocker reach over the rim.",
         "Losing the ball by not extending far enough across."],
        ["Cross under", "Protect with the rim", "High off glass"],
        "If the help commits to the reverse, drop it to the dunker-spot cutter.",
        "A must-have for craft finishers attacking from the baseline."),
    _skill("pro-hop", "Pro Hop", "Finishing", "Advanced",
        "When a help defender steps into your driving lane and you need to hop past them laterally.",
        "A two-foot gather hop lets you shift your whole body sideways to a new angle and stay balanced.",
        ["Gather the ball off two feet with a wide, low hop.",
         "Hop laterally away from the defender's contest.",
         "Keep the ball tight and protected during the hop.",
         "Rise and finish off two feet from the new angle."],
        ["Traveling by picking the ball up before the hop.",
         "Hopping too high and losing power and balance."],
        ["Two-foot gather", "Hop sideways", "Finish balanced"],
        "If the defender slides across with you, use an up-and-under or reverse finish.",
        "A powerful counter for strong finishers absorbing contact in the paint."),
    # ---------------- PLAYMAKING ----------------
    _skill("pnr-read", "Pick-and-Roll Reads", "Playmaking", "Advanced",
        "Every time you run a ball screen - the read decides whether you score or create for others.",
        "Reading the two defenders in the action lets you punish whatever coverage they choose.",
        ["Set up your defender before using the screen (walk them in).",
         "Read the big: if they drop, shoot the pull-up; if they hedge, split or reject.",
         "If both defenders commit to you, hit the roller in the pocket.",
         "If the low man tags the roll, kick to the open weak-side shooter."],
        ["Picking up your dribble too early and killing the read.",
         "Forcing a pass into a coverage that took it away."],
        ["Set up the screen", "Read the big", "Punish the help"],
        "Against a switch, attack the mismatch (drive the big, post the guard).",
        "The engine of point guards and pick-and-roll maestros running an offense."),
    _skill("pocket-pass", "Pocket Pass", "Playmaking", "Intermediate",
        "When a big is rolling to the rim and the drop defender opens a window near your hip.",
        "A low, one-hand pocket pass slips the ball to the roller through a tight gap before help arrives.",
        ["Keep your live dribble as you turn the corner off the screen.",
         "Drop your dribble hand low into the 'pocket' near your hip.",
         "Fire a firm one-hand bounce or air pass to the roller's chest/hands.",
         "Lead the roller so they catch it in stride toward the rim."],
        ["Telegraphing with a two-hand wind-up.",
         "Throwing behind the roller so they lose momentum."],
        ["Keep it live", "Low and quick", "Lead the roller"],
        "If the low man jumps the pocket, skip it to the weak-side corner shooter.",
        "The signature dime of pick-and-roll maestros and passing bigs' guards."),
    _skill("hesitation", "Hesitation (Hesi)", "Playmaking", "Beginner",
        "When attacking a back-pedaling defender who is giving you a cushion.",
        "A hesitation freezes the defender's feet for a split second so you can accelerate past them.",
        ["Attack with pace, then briefly slow and stand slightly taller (the hesi).",
         "Show a subtle scoring or passing threat to hold their attention.",
         "Explode back to full speed the instant their feet settle.",
         "Keep the ball on a string through the change of pace."],
        ["Slowing down too much and letting the defender reset.",
         "Standing fully upright, which loses your driving base."],
        ["Change speed, not direction", "Freeze the feet", "Then go"],
        "If they don't bite, chain into a crossover or step-back for the shot.",
        "A pace-manipulation tool that makes downhill creators unpredictable."),
    _skill("change-of-pace", "Change of Pace", "Playmaking", "Intermediate",
        "Throughout a possession to keep the defender guessing on speed and rhythm.",
        "Alternating fast and slow bursts breaks the defender's timing and creates driving lanes without a move.",
        ["Dribble at 60% to lull the defender into matching your speed.",
         "Explode to 100% off a hard plant when you see them relax.",
         "Use subtle body language to disguise the shift.",
         "Return to controlled pace to reset if the lane closes."],
        ["Playing at one constant speed, which is easy to guard.",
         "Only having one gear (all fast or all slow)."],
        ["Lull then burst", "Disguise the shift", "Two clear gears"],
        "Pair with a hesitation or in-and-out for a lethal downhill package.",
        "The trademark of pace manipulators who control tempo on every touch."),
    # ---------------- DEFENSE ----------------
    _skill("closeout", "Closeout", "Defense", "Beginner",
        "When your assignment catches the ball and you must recover from help position.",
        "A controlled closeout contests the shot without giving up a straight-line drive.",
        ["Sprint the first two-thirds of the distance, then chop your feet to break down.",
         "Come to balance with a high hand on the shooting side.",
         "Stay low with a wide base, weight back on your heels-to-mid-foot.",
         "Force the ball-handler toward help or their weak hand."],
        ["Running full-speed all the way and flying by the shooter.",
         "Closing out high and straight, giving up the drive."],
        ["Sprint then break down", "High hand", "Force one way"],
        "If they shot-fake, stay down and slide - don't leave your feet.",
        "The foundation of team defense for two-way wings and lockdown guards."),
    _skill("defensive-slide", "Defensive Slide", "Defense", "Beginner",
        "Any time you're guarding the ball on the perimeter and staying in front of a driver.",
        "A low, wide slide keeps you between your man and the rim without crossing your feet.",
        ["Stay in a low athletic stance with feet wider than shoulders.",
         "Push off the trail foot and step with the lead foot in the direction of the drive.",
         "Never bring your feet together or cross them.",
         "Keep your chest square and active hands down and ready."],
        ["Crossing your feet, which lets the driver blow by.",
         "Standing too tall and losing lateral quickness."],
        ["Stay low", "Push and step", "Never cross feet"],
        "If beaten, open your hips and sprint to re-establish position, then re-square.",
        "The core movement of every on-ball defender and lockdown guard."),
    _skill("box-out", "Box Out", "Defense", "Beginner",
        "On every shot attempt to secure the rebound and end the defensive possession.",
        "Making contact and sealing your man off the glass wins possessions that don't show in the box score.",
        ["Find your man as the shot goes up, don't ball-watch.",
         "Make contact by pivoting and putting your backside into them.",
         "Keep a wide base with elbows out and knees bent.",
         "Go get the ball at its highest point once you've sealed."],
        ["Watching the ball and losing your man.",
         "Boxing out but never actually pursuing the rebound."],
        ["Find your man", "Make contact", "Then go get it"],
        "Against a crasher who spins off, re-hit and re-seal before pursuing.",
        "The unglamorous key to defense for glass cleaners and rim protectors."),
    # ---------------- POST ----------------
    _skill("dropstep", "Drop Step", "Post", "Intermediate",
        "When posting up and the defender leans on one side of your back.",
        "Feeling the defender's pressure and drop-stepping baseline gets you a quick, powerful finish at the rim.",
        ["Establish a deep, wide post seal with a target hand.",
         "Feel which side the defender is playing.",
         "Drop-step your baseline foot back and pivot into the open space.",
         "Finish strong off two feet with the ball high."],
        ["Dribbling too much and letting help arrive.",
         "Drop-stepping into the defender instead of the open side."],
        ["Feel the defender", "Drop to open space", "Finish strong"],
        "If the help digs, kick to the weak-side shooter or use a jump hook over the top.",
        "A go-to move for post scorers and back-to-the-basket bigs."),
    _skill("jump-hook", "Jump Hook", "Post", "Intermediate",
        "When a defender is between you and the rim in the post and can't be beaten with power.",
        "A high jump hook releases the ball over the defender's reach with a soft, un-blockable arc.",
        ["Seal your man and receive the entry on the block.",
         "Turn into the lane off your pivot foot, ball protected high.",
         "Rise off two feet or the inside foot, extending the ball overhead.",
         "Release with a soft flick off the fingertips, following through."],
        ["Bringing the ball low where it can be dug out.",
         "Shooting flat instead of arcing it over the defender."],
        ["Ball high", "Rise and extend", "Soft arc"],
        "If the defender fronts high, use a drop step or up-and-under instead.",
        "The reliable go-to for post scorers and passing bigs finishing over length."),
    _skill("face-up-jab", "Face-Up Jab Series", "Post", "Intermediate",
        "When you catch facing the rim from the mid-post or elbow with space to read the defender.",
        "A hard jab step forces the defender to commit, opening a drive, shot, or counter.",
        ["Catch and face up in a low triple-threat stance.",
         "Jab hard at the defender's front foot to read their reaction.",
         "If they retreat, rise into the jumper.",
         "If they crowd, blow by with a long first step the other way."],
        ["Jabbing softly so the defender doesn't respect it.",
         "Standing upright and losing your driving base."],
        ["Hard jab", "Read the reaction", "Shot or drive"],
        "If they play the drive and shot even, use a shot-fake into a one-dribble pull-up.",
        "A versatile mid-post weapon for stretch fours and mismatch hunters."),
    _skill("spin-move", "Spin Move", "Post", "Advanced",
        "When a defender overplays your strong-side shoulder in the post or on a drive.",
        "A quick spin uses the defender's pressure against them, whipping you to the open side to finish.",
        ["Feel or see the defender leaning on one shoulder.",
         "Plant your pivot foot and spin your body away from the pressure.",
         "Keep the ball tight to your torso through the turn.",
         "Come out of the spin rising into a finish at the rim."],
        ["Spinning too wide and exposing the ball.",
         "Losing balance and finishing off-platform."],
        ["Feel the lean", "Ball tight", "Spin and finish"],
        "If a helper steps to the spin, kick out or reverse-pivot back to your original side.",
        "An explosive counter for post scorers and rim attackers facing an over-eager defender."),
]

# ~20 elite historical & modern players
PLAYERS = [
    {"id": "stephen-curry", "name": "Stephen Curry", "era": "Modern", "position": "PG",
     "archetype": "Movement Sniper",
     "traits": ["Limitless deep range", "Elite off-ball movement", "Lightning-quick release", "Tight low handle", "Relentless conditioning", "Gravity that warps defenses"],
     "steal": ["Come off screens with feet already set", "Never stop moving without the ball", "Shoot on the way up, not at the peak"],
     "study": "The blueprint for how off-ball movement and range bend an entire defense."},
    {"id": "kevin-durant", "name": "Kevin Durant", "era": "Modern", "position": "SF",
     "archetype": "Three-Level Scorer",
     "traits": ["Unblockable high release", "7-foot guard skills", "Pure midrange mastery", "Efficient shot selection", "Silky pull-up", "Length on defense"],
     "steal": ["Use your height to shoot over, not around", "Master the midrange pull-up", "Get to your spots with two dribbles"],
     "study": "The purest scorer - size plus guard skill makes every shot available."},
    {"id": "lebron-james", "name": "LeBron James", "era": "Modern", "position": "SF",
     "archetype": "Point Forward",
     "traits": ["Freight-train downhill drives", "Elite court vision", "Physical dominance", "High basketball IQ", "Transition force", "Longevity"],
     "steal": ["Play with pace and force in transition", "See the whole floor before you catch", "Use your body to shield the ball"],
     "study": "The ultimate playmaking forward - power, vision, and control of tempo."},
    {"id": "michael-jordan", "name": "Michael Jordan", "era": "All-Time", "position": "SG",
     "archetype": "Iso Technician",
     "traits": ["Unstoppable fadeaway", "Elite footwork", "Killer competitiveness", "Two-way dominance", "Midrange mastery", "Clutch gene"],
     "steal": ["Master your footwork and pivots", "Develop a reliable fadeaway", "Attack the same way at game speed every rep"],
     "study": "The standard for iso scoring, footwork, and competitive will."},
    {"id": "kobe-bryant", "name": "Kobe Bryant", "era": "All-Time", "position": "SG",
     "archetype": "Iso Sniper",
     "traits": ["Footwork perfectionist", "Deep shot-creation bag", "Mamba mentality", "Elite jab series", "Midrange assassin", "Relentless work ethic"],
     "steal": ["Build a deep bag of counters", "Perfect your footwork with detail", "Study the greats before you"],
     "study": "The most detailed footwork and shot-creation study in the game."},
    {"id": "magic-johnson", "name": "Magic Johnson", "era": "All-Time", "position": "PG",
     "archetype": "Floor General",
     "traits": ["6-9 point guard vision", "Flawless open-court passing", "Post-up guard", "Leadership", "Transition brilliance", "Winning IQ"],
     "steal": ["Push tempo and find runners early", "See passes a beat before they open", "Use size to post smaller guards"],
     "study": "How size and vision at the point create an unstoppable transition game."},
    {"id": "larry-bird", "name": "Larry Bird", "era": "All-Time", "position": "SF",
     "archetype": "Clutch Shot Maker",
     "traits": ["Deadeye shooting", "Elite passing forward", "Trash-talk confidence", "Basketball IQ", "Clutch shot-making", "Deceptive craft"],
     "steal": ["Get your feet set and shoot with confidence", "Pass out of the post", "Know the moment and want the shot"],
     "study": "Shooting touch and IQ from the forward spot with ice in clutch moments."},
    {"id": "tim-duncan", "name": "Tim Duncan", "era": "All-Time", "position": "PF",
     "archetype": "Two-Way Big",
     "traits": ["Perfect bank shot", "Fundamental footwork", "Elite help defense", "Rebounding", "Consistency", "Quiet leadership"],
     "steal": ["Master the bank shot angles", "Use fundamentals over flash", "Anchor the defense with positioning"],
     "study": "The most fundamentally sound big man - footwork and two-way consistency."},
    {"id": "shaquille-oneal", "name": "Shaquille O'Neal", "era": "All-Time", "position": "C",
     "archetype": "Post Scorer",
     "traits": ["Overwhelming power", "Deep post seals", "Drop-step finisher", "Rim gravity", "Rebounding", "Rim protection"],
     "steal": ["Establish deep post position early", "Finish through contact with two hands", "Use your body to seal space"],
     "study": "The most dominant paint force - power post scoring at its peak."},
    {"id": "hakeem-olajuwon", "name": "Hakeem Olajuwon", "era": "All-Time", "position": "C",
     "archetype": "Post Scorer",
     "traits": ["Legendary Dream Shake", "Elite footwork", "Shot-blocking", "Face-up game", "Soft touch", "Two-way brilliance"],
     "steal": ["Build a footwork-based post bag", "Sell fakes with your shoulders", "Combine power with finesse"],
     "study": "The gold standard for post footwork and counters - the Dream Shake."},
    {"id": "giannis-antetokounmpo", "name": "Giannis Antetokounmpo", "era": "Modern", "position": "PF",
     "archetype": "Downhill Creator",
     "traits": ["Freakish length and stride", "Downhill force", "Transition dominance", "Improving jumper", "Elite finishing", "Rim protection"],
     "steal": ["Cover ground with long strides", "Attack the rim in transition", "Use length to finish over defenders"],
     "study": "How length and downhill force overwhelm defenses without a jumper."},
    {"id": "nikola-jokic", "name": "Nikola Jokic", "era": "Modern", "position": "C",
     "archetype": "Passing Big",
     "traits": ["Elite big-man passing", "Deceptive footwork", "Soft touch", "High IQ reads", "Rebounding", "Unshakable poise"],
     "steal": ["Read the whole floor from the elbow", "Use touch over athleticism", "Slow the game down mentally"],
     "study": "The redefinition of the center as an offensive hub and passer."},
    {"id": "luka-doncic", "name": "Luka Doncic", "era": "Modern", "position": "PG",
     "archetype": "Pick-and-Roll Maestro",
     "traits": ["Elite step-back", "Pace manipulation", "Pick-and-roll mastery", "Craft over speed", "Vision", "Clutch scoring"],
     "steal": ["Manipulate pace instead of relying on speed", "Master the step-back", "Read the second defender in the PnR"],
     "study": "How craft, pace, and size beat pure athleticism in the pick-and-roll."},
    {"id": "kawhi-leonard", "name": "Kawhi Leonard", "era": "Modern", "position": "SF",
     "archetype": "Two-Way Wing",
     "traits": ["Lockdown defense", "Midrange mastery", "Huge hands", "Efficient scoring", "Calm demeanor", "Clutch shot-making"],
     "steal": ["Defend with active hands and positioning", "Master the midrange", "Stay composed under pressure"],
     "study": "The complete two-way wing - elite defense paired with efficient scoring."},
    {"id": "james-harden", "name": "James Harden", "era": "Modern", "position": "SG",
     "archetype": "Iso Sniper",
     "traits": ["Elite step-back three", "Foul-drawing craft", "Left-hand mastery", "Pace control", "Passing", "Deep bag"],
     "steal": ["Master the step-back three", "Change pace to create fouls", "Develop your off-hand"],
     "study": "The modern iso scorer - step-backs, pace, and foul-drawing craft."},
    {"id": "allen-iverson", "name": "Allen Iverson", "era": "All-Time", "position": "PG",
     "archetype": "Handle Artist",
     "traits": ["Devastating crossover", "Fearless finishing", "Blazing speed", "Heart over size", "Scoring bag", "Iconic handle"],
     "steal": ["Sell your crossover with your whole body", "Play bigger than your size", "Attack fearlessly at the rim"],
     "study": "The purest handle and heart - how a smaller guard dominates."},
    {"id": "dirk-nowitzki", "name": "Dirk Nowitzki", "era": "All-Time", "position": "PF",
     "archetype": "Stretch Four",
     "traits": ["Signature one-leg fadeaway", "Elite shooting big", "Footwork", "Clutch scoring", "Longevity", "Unblockable release"],
     "steal": ["Develop a signature un-blockable shot", "Stretch the floor as a big", "Master one-leg balance"],
     "study": "The archetype for the shooting big and the un-guardable fadeaway."},
    {"id": "chris-paul", "name": "Chris Paul", "era": "Modern", "position": "PG",
     "archetype": "Floor General",
     "traits": ["Elite midrange", "Masterful PnR control", "High IQ", "Pace mastery", "Leadership", "Clutch decision-making"],
     "steal": ["Control tempo and the game clock", "Master the midrange pull-up", "Set up teammates in their spots"],
     "study": "The ultimate floor general - pace, control, and pick-and-roll mastery."},
    {"id": "scottie-pippen", "name": "Scottie Pippen", "era": "All-Time", "position": "SF",
     "archetype": "Two-Way Wing",
     "traits": ["Elite perimeter defense", "Point-forward skills", "Transition force", "Length", "Versatility", "High IQ"],
     "steal": ["Defend multiple positions", "Push the ball as a forward", "Use length to disrupt passing lanes"],
     "study": "The versatile two-way forward - defense, playmaking, and transition."},
    {"id": "damian-lillard", "name": "Damian Lillard", "era": "Modern", "position": "PG",
     "archetype": "Deep-Range Sniper",
     "traits": ["Logo-range pull-up", "Clutch gene", "Quick release", "Pick-and-roll scoring", "Deep bag", "Fearless shot-making"],
     "steal": ["Extend your range with balance", "Rise with confidence from deep", "Own the clutch moments"],
     "study": "How deep range and a clutch mentality break defenses late in games."},
]
